import { ServiceCategory, ServiceProvider, Booking, JobStatus, NotificationItem } from "./types";
import fixitDiagnosticImg from "./assets/images/regenerated_image_1785074055350.png";

export const SERVICE_CATEGORIES: ServiceCategory[] = [
  {
    id: "electrician",
    nameEn: "Electrician",
    nameNe: "बिजुली मिस्त्री",
    iconName: "Plug",
    color: "#3038A4", // Royal Blue
    descEn: "Short circuits, wiring repairs, and appliance setup",
    descNe: "सर्ट सर्किट, वाइरिङ मर्मत, र उपकरण जडान",
    priceEn: "Rs. 400 onwards",
    priceNe: "रु ४०० देखि सुरु",
  },
  {
    id: "plumber",
    nameEn: "Plumber",
    nameNe: "प्लम्बर",
    iconName: "Droplets",
    color: "#004021", // Forest Green
    descEn: "Leaking pipes, tap installations, and drainage blockages",
    descNe: "पानी चुहावट, धारा जडान, र ढल निकास सफाइ",
    priceEn: "Rs. 350 onwards",
    priceNe: "रु ३५० देखि सुरु",
  },
  {
    id: "handyman",
    nameEn: "Handyman",
    nameNe: "ह्यान्डीम्यान",
    iconName: "Wrench",
    color: "#D7911D", // Gold
    descEn: "Furniture assembly, wall drilling, and locks repair",
    descNe: "दराज जडान, भित्तामा ड्रिलिङ, र ढोकाको लक मर्मत",
    priceEn: "Rs. 300 onwards",
    priceNe: "रु ३०० देखि सुरु",
  },
  {
    id: "preiaction",
    nameEn: "Pest Control",
    nameNe: "कीटनाशक सेवा",
    iconName: "Paintbrush",
    color: "#8E1851", // Deep Magenta
    descEn: "Pest control, sanitization, and room painting",
    descNe: "कीटनाशक स्प्रे, सेनिटाइजेसन, र कोठा रंगरोगन",
    priceEn: "Rs. 800 onwards",
    priceNe: "रु ८०० देखि सुरु",
  },
  {
    id: "haracomert",
    nameEn: "Home Care",
    nameNe: "गृह हेरचाह र सफाइ",
    iconName: "Sparkles",
    color: "#004021", // Forest Green
    descEn: "Full house cleaning, vacuuming, and water tank washing",
    descNe: "घर सफाइ, भ्याकुम गर्ने, र पानीको ट्याङ्की धुने",
    priceEn: "Rs. 1,200 onwards",
    priceNe: "रु १,२०० देखि सुरु",
  },
  {
    id: "oahar",
    nameEn: "Consultation",
    nameNe: "सलाह र परामर्श",
    iconName: "MessageSquare",
    color: "#3038A4", // Royal Blue
    descEn: "Expert consultation and repair estimate support",
    descNe: "विशेषज्ञ परामर्श र मर्मत खर्च अनुमान सेवा",
    priceEn: "Rs. 150 onwards",
    priceNe: "रु १५० देखि सुरु",
  },
];

export const SERVICE_PROVIDERS: ServiceProvider[] = [
  {
    id: "p1",
    name: "Sita Rai",
    category: "haracomert",
    rating: 4.7,
    completedJobs: 142,
    phone: "9851012345",
    avatarUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150",
  },
  {
    id: "p2",
    name: "Ramesh Khadka",
    category: "plumber",
    rating: 4.9,
    completedJobs: 310,
    phone: "9841234567",
    avatarUrl: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150",
  },
  {
    id: "p3",
    name: "Sunita Tamang",
    category: "electrician",
    rating: 4.8,
    completedJobs: 185,
    phone: "9860111222",
    avatarUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150",
  },
  {
    id: "p4",
    name: "Karan Shrestha",
    category: "handyman",
    rating: 4.6,
    completedJobs: 98,
    phone: "9812345678",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150",
  },
];

export const INITIAL_BOOKINGS: Booking[] = [
  {
    id: "b-01",
    categoryId: "haracomert",
    categoryName: "Home Care",
    technicianName: "Sita Rai",
    technicianPhone: "9851012345",
    technicianAvatar: "https://images.unsplash.com/photo-1540569014015-19a7be504e3a?w=150",
    problemScale: "Moderate",
    problemDetails: "Full Deep House Maid Service - 4 Rooms",
    status: JobStatus.COMPLETED,
    date: "2026-06-20",
    cost: "Rs. 11,000",
    address: "Baneshwor-10, Kathmandu",
    isAiDiagnostic: false,
    applianceName: "Living Room Flooring",
    nextServicingIntervalDays: 180,
    nextServicingReminderDate: "2026-12-17",
  },
  {
    id: "b-02",
    categoryId: "plumber",
    categoryName: "Plumber",
    technicianName: "Ramesh Khadka",
    technicianPhone: "9841234567",
    technicianAvatar: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150",
    problemScale: "Major",
    problemDetails: "Full Bathroom Set Installation & Sewer Drain setup",
    status: JobStatus.COMPLETED,
    date: "2026-06-15",
    cost: "Rs. 32,500",
    address: "Pulchowk, Lalitpur",
    isAiDiagnostic: true,
    diagnosticDetails: {
      problemIdentified: "Bathroom installation with minor pipeline leaks",
      estimatedCostRange: "Rs. 30,000 - Rs. 35,000",
      recommendedFixer: "Plumber",
      severity: "Major",
      immediateSteps: [
        "Check all brass gaskets before turning on valves",
        "Clear drainage path to avoid initial blockages",
        "Monitor valve seal ring pressure"
      ]
    },
    applianceName: "Geyser & Main Water Pump",
    nextServicingIntervalDays: 90,
    nextServicingReminderDate: "2026-09-13",
  },
];

export const PRESET_DIAGNOSTICS = [
  {
    key: "leaky_tap",
    nameEn: "Leaking Faucet / Pipe Joint",
    nameNe: "पानी चुहावट भएको धारा",
    imageUrl: fixitDiagnosticImg,
    descEn: "Standard dripping bathroom tap or loose joint pipe",
    descNe: "धारा वा पाइपको जोडबाट पानी निरन्तर चुहिरहेको",
  },
  {
    key: "exposed_wire",
    nameEn: "Exposed Wire Sparking",
    nameNe: "बिजुलीको खुल्ला तार",
    imageUrl: "https://images.unsplash.com/photo-1455162015907-a5817e793cb0?w=400&auto=format&fit=crop&q=60",
    descEn: "Loose wires hanging from power sockets causing sparks",
    descNe: "बिजुलीको सकेटबाट बाहिर निस्किएका स्पार्क निस्किने तारहरू",
  },
  {
    key: "broken_ac",
    nameEn: "Air Conditioner Dripping",
    nameNe: "एसीबाट पानी चुहिएको",
    imageUrl: "https://images.unsplash.com/photo-1527018601619-a508a2be00cd?w=400&auto=format&fit=crop&q=60",
    descEn: "Indoor AC unit not cooling and dripping water down the wall",
    descNe: "भित्री एसी एकाईले चिसो नगरेको र भित्तामा पानी चुहाएको",
  },
  {
    key: "termite",
    nameEn: "Termite Furniture Damage",
    nameNe: "काठमा धमिरा लागेको",
    imageUrl: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=400&auto=format&fit=crop&q=60",
    descEn: "Wood pests destroying cabinet frames and door borders",
    descNe: "धमिराले घरको दराज वा ढोकाको काठ खाइरहेको",
  },
];

export const TRANSLATIONS = {
  en: {
    appName: "Najikko Sathi",
    serviceCategories: "Service Categories",
    searchPlaceholder: "Search for Local Service Providers...",
    featuredServices: "Featured Services",
    popularServices: "Popular Services",
    viewMore: "view more",
    loginTitle: "Welcome Back",
    loginSubtitle: "Welcome back to Nepal's local fixer platform",
    inputPhoneEmail: "Mobile Number / Email",
    inputPassword: "Password",
    btnLogin: "Login",
    orContinueWith: "Or, continue with...",
    btnGoogle: "Continue with Google",
    btnApple: "Continue with Apple",
    btnFacebook: "Continue with Facebook",
    btnEmail: "Continue with other Email",
    signUp: "Sign Up",
    forgotPassword: "Forgot Password?",
    navHome: "Home",
    navBookings: "Bookings",
    navFixitAi: "AI Sathi",
    navTracking: "Tracking",
    navProfile: "Profile",
    navCustomerSupport: "Customer Support",
    navSettings: "Settings",
    navSignOut: "Sign Out",
    navMyProfile: "My Profile",
    bookingIssues: "Booking Issues",
    paymentQuestions: "Payment Questions",
    serviceFeedback: "Service Feedback",
    profileHelp: "Profile Help",
    startLiveChat: "Start a Live Chat",
    commonQuestions: "Common Questions",
    footerEmail: "Email",
    btnCallUs: "Call Us",
    howCanWeHelp: "How can we help? Search for an issue or topic...",
    supportTitle: "Customer Support",
    problemIdentified: "Problem Identified",
    estimatedCost: "Estimated Cost Range",
    recommendedFixer: "Recommended Fixer",
    severity: "Severity",
    immediateSteps: "Immediate Steps",
    bookNow: "Book Now",
    bookingSummary: "Booking Summary",
    bookingConfirmSuccess: "Booking Confirmed!",
    technicianAssigned: "Technician Dispatched & tracking live!",
    etaCountdown: "Arrival ETA",
    mins: "mins",
    callTechnician: "Call Fixer",
    statusDispatched: "Technician Dispatched",
    statusArriving: "Arriving in 5 Mins",
    statusArrived: "Worker Arrived at Location",
    statusInProgress: "Job In Progress",
    statusCompleted: "Job Completed",
    noActiveTracking: "No Active Tracking",
    trackingDescription: "Book a new service or look at past bookings. Live tracking will display here once a technician is dispatched.",
    bookingsLedger: "Bookings Ledger",
    smartReminders: "Smart Appliance Reminders",
    dueIn: "Due in",
    days: "days",
    dueToday: "Service Due Today!",
    scheduleService: "Schedule Routine Check",
    newBookingTitle: "Book Local Technician",
    problemScale: "Problem Scale",
    minor: "Minor (Small Leak/Wire Repair)",
    moderate: "Moderate (Standard servicing)",
    major: "Major (Complete installation/failure)",
    addressLabel: "Service Address",
    enterAddress: "Enter your home address",
    descPlaceholder: "Describe the issue in detail (optional)",
    cancel: "Cancel",
    confirmBooking: "Confirm Booking",
    notificationLabel: "Notifications",
    languageToggle: "नेपाली (Switch to Nepali)",
    languageLabel: "App Language",
    activeJobBanner: "Active Job: Technician is on the way!",
    fixitAiPrompt: "Simulate taking or uploading a photo of a household issue to get instant AI Sathi diagnostic report, price projection, and direct fixer booking.",
    unlockedFixer: "Book Recommended Fixer",
  },
  ne: {
    appName: "नजिकको साथी",
    serviceCategories: "सेवा कोटिहरू",
    searchPlaceholder: "स्थानीय सेवा प्रदायक खोज्नुहोस्...",
    featuredServices: "विशेष सेवाहरू",
    popularServices: "लोकप्रिय सेवाहरू",
    viewMore: "थप हेर्नुहोस्",
    loginTitle: "स्वागत छ",
    loginSubtitle: "नेपालको स्थानीय मिस्त्री र सेवा प्रदायक प्लेटफर्ममा स्वागत छ",
    inputPhoneEmail: "मोबाइल नम्बर / इमेल",
    inputPassword: "पासवर्ड",
    btnLogin: "लगइन गर्नुहोस्",
    orContinueWith: "वा, यसबाट अगाडि बढ्नुहोस्...",
    btnGoogle: "गुगल मार्फत जारी राख्नुहोस्",
    btnApple: "एप्पल मार्फत जारी राख्नुहोस्",
    btnFacebook: "फेसबुक मार्फत जारी राख्नुहोस्",
    btnEmail: "अन्य इमेल मार्फत जारी राख्नुहोस्",
    signUp: "नयाँ खाता खोल्नुहोस्",
    forgotPassword: "पासवर्ड बिर्सनुभयो?",
    navHome: "घर",
    navBookings: "बुकिङ",
    navFixitAi: "एआई साथी",
    navTracking: "ट्र्याकिङ",
    navProfile: "प्रोफाइल",
    navCustomerSupport: "ग्राहक सहायता",
    navSettings: "सेटिङहरू",
    navSignOut: "साइन आउट",
    navMyProfile: "मेरो प्रोफाइल",
    bookingIssues: "बुकिङ समस्या",
    paymentQuestions: "भुक्तानी प्रश्नहरू",
    serviceFeedback: "सेवा प्रतिक्रिया",
    profileHelp: "प्रोफाइल सहायता",
    startLiveChat: "लाइभ च्याट सुरु गर्नुहोस्",
    commonQuestions: "साधारण प्रश्नहरू",
    footerEmail: "इमेल",
    btnCallUs: "कल गर्नुहोस्",
    howCanWeHelp: "हामी कसरी मद्दत गर्न सक्छौं? खोज्नुहोस्...",
    supportTitle: "ग्राहक सहायता",
    problemIdentified: "पहिचान गरिएको समस्या",
    estimatedCost: "अनुमानित लागत दायरा",
    recommendedFixer: "सिफारिस गरिएको मिस्त्री",
    severity: "गम्भीरता",
    immediateSteps: "तत्काल चाल्नुपर्ने कदमहरू",
    bookNow: "अहिले बुकिङ गर्नुहोस्",
    bookingSummary: "बुकिङ विवरण",
    bookingConfirmSuccess: "बुकिङ सुनिश्चित भयो!",
    technicianAssigned: "प्राविधिक पठाइयो र लाइभ ट्र्याकिङ सक्रिय छ!",
    etaCountdown: "आइपुग्ने समय",
    mins: "मिनेट",
    callTechnician: "कल गर्नुहोस्",
    statusDispatched: "प्राविधिक पठाइयो",
    statusArriving: "५ मिनेटमा आइपुग्दै",
    statusArrived: "प्राविधिक आइपुग्नुभयो",
    statusInProgress: "काम हुँदैछ",
    statusCompleted: "काम सम्पन्न भयो",
    noActiveTracking: "कुनै सक्रिय ट्र्याकिङ छैन",
    trackingDescription: "नयाँ सेवा बुक गर्नुहोस् वा विगतका बुकिङहरू हेर्नुहोस्। प्राविधिक पठाइएपछि यहाँ लाइभ ट्र्याकिङ देखिनेछ।",
    bookingsLedger: "बुकिङ खाता",
    smartReminders: "स्मार्ट उपकरण मर्मत सम्झाउनी",
    dueIn: "समय बाँकी",
    days: "दिन",
    dueToday: "आजै मर्मत गर्ने दिन!",
    scheduleService: "नियमित जाँच तालिका",
    newBookingTitle: "स्थानीय प्राविधिक बुकिङ गर्नुहोस्",
    problemScale: "समस्याको गम्भीरता",
    minor: "सामान्य (सानो चुहावट/तार मर्मत)",
    moderate: "मध्यम (साधारण मर्मत र सफाइ)",
    major: "गम्भीर (पूर्ण रूपमा बिग्रिएको/नयाँ जडान)",
    addressLabel: "सेवा ठेगाना",
    enterAddress: "आफ्नो घरको ठेगाना राख्नुहोस्",
    descPlaceholder: "समस्याको बारेमा विस्तृत विवरण दिनुहोस् (वैकल्पिक)",
    cancel: "रद्द गर्नुहोस्",
    confirmBooking: "बुकिङ निश्चित गर्नुहोस्",
    notificationLabel: "सूचनाहरू",
    languageToggle: "English (अंग्रेजीमा स्विच गर्नुहोस्)",
    languageLabel: "एपको भाषा",
    activeJobBanner: "सक्रिय काम: प्राविधिक बाटोमा हुनुहुन्छ!",
    fixitAiPrompt: "घरको समस्याको फोटो खिच्नुहोस् वा अपलोड गर्नुहोस्। एआई साथी मार्फत तत्काल पहिचान, अनुमानित खर्च र बुकिङ सेवा प्राप्त गर्नुहोस्।",
    unlockedFixer: "सिफारिस गरिएको मिस्त्री बुक गर्नुहोस्",
  },
};
